# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: 'X.Y{.Z}'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set version tag
      run: |
        git tag -f v${{ github.event.inputs.version }}
        git push -f origin v${{ github.event.inputs.version }}

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
  
    - name: Restore Packages
      run: nuget restore AmazonScrapper.sln

    - name: Build solution
      run: msbuild AmazonScrapper\AmazonScrapper.csproj -t:rebuild -property:Configuration=Release
      
    - name: Package Files
      run: powershell Compress-Archive -Path 'AmazonScrapper\bin\Release\AmazonScrapper.exe', 'AmazonScrapper\bin\Release\*.dll', 'AmazonScrapper\bin\Release\*.png', 'Python\*.ini', 'Python\*.py' -DestinationPath 'AmazonScrapper.zip' -Force
         
    - name: Rename to crplugin
      run: ren  AmazonScrapper.zip AmazonScrapper.crplugin
      
    - name: Release
      uses: ncipollo/release-action@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: false
        artifactErrorsFailBuild: true
        draft: true
        prerelease: false
        commit: ${{ github.ref_name }}
        tag: 'v${{ github.event.inputs.version }}'
        artifacts: "AmazonScrapper.crplugin"
